name: PR Compliancy
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_semver_labels:
    name: Check Semver labels
    runs-on: "ubuntu-latest"
    steps:
      - name: Check for Semver labels
        uses: danielchabr/pr-labels-checker@v3.2
        with:
          hasSome: major,minor,patch
          githubToken: ${{ secrets.GITHUB_TOKEN }}
