name: Labels - Synchronize
"on":
  push:
    paths:
      - .github/labels.yml
  workflow_dispatch: {}
jobs:
  synchronize:
    name: Synchronize Labels
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
